// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGKvCKyW2X0g9eV7g-lWhUHX3RdYcbxc',
    appId: '1:152557412847:web:3d538acd8d603b00ef961a',
    messagingSenderId: '152557412847',
    projectId: 'device-80261',
    authDomain: 'device-80261.firebaseapp.com',
    databaseURL: 'https://device-80261.firebaseio.com',
    storageBucket: 'device-80261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjQpOe8RnkMqJJY3ZSaxCW7orcr0Hkrk8',
    appId: '1:152557412847:android:7a915032b8ae226fef961a',
    messagingSenderId: '152557412847',
    projectId: 'device-80261',
    databaseURL: 'https://device-80261.firebaseio.com',
    storageBucket: 'device-80261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp3OunUshHZb1yoAQrCKqg9iadjjI1SXU',
    appId: '1:152557412847:ios:8c1fd495f461f278ef961a',
    messagingSenderId: '152557412847',
    projectId: 'device-80261',
    databaseURL: 'https://device-80261.firebaseio.com',
    storageBucket: 'device-80261.appspot.com',
    androidClientId: '152557412847-m77pa0n83a7sgrabh68sfut0a6a03bra.apps.googleusercontent.com',
    iosClientId: '152557412847-tvjlm49a6oqc5pnan4a5tp1t7lq574ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp3OunUshHZb1yoAQrCKqg9iadjjI1SXU',
    appId: '1:152557412847:ios:4046f39d74abb14fef961a',
    messagingSenderId: '152557412847',
    projectId: 'device-80261',
    databaseURL: 'https://device-80261.firebaseio.com',
    storageBucket: 'device-80261.appspot.com',
    androidClientId: '152557412847-m77pa0n83a7sgrabh68sfut0a6a03bra.apps.googleusercontent.com',
    iosClientId: '152557412847-r3v9e8e1qeoqv7hatdjo9q54v1bl0aaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin.RunnerTests',
  );
}
